language: java
jdk:
  - openjdk7
  - oraclejdk8

addons:
  apt:
    packages:
      - openjdk-7-jre
      
script: for mod in cadc-access-control  cadc-access-control-identity  cadc-access-control-server cadc-access-control-admin cadc-tomcat; do cd $mod; gradle wrapper --gradle-version 2.11; ./gradlew --info build javadoc install || break -1; cd ..; done


