language: java
jdk:
  - openjdk7
  - oraclejdk8

script: for mod in cadc-access-control  cadc-access-control-identity  cadc-access-control-server cadc-access-control-admin cadc-tomcat; do cd $mod; gradle -Djavax.net.debug=ssl:handshake --stacktrace build javadoc install || break -1; cd ..; done


